server:
  port: 9301
spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_URL}/environment
ldap:
  contextSource:
    url: ${LDAP_URL}
    userDn: cn=admin,dc=moserp,dc=org
    password: Nosfols6

