name: inventory
version: 1.0.0
author: Thomas Letsch <contact@thomas-letsch.de>
homepage: http://www.thomas-letsch.de
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  polymer: '>=0.16.0 <0.17.0'
  core_elements: '>=0.7.1 <0.8.0'
  paper_elements: '>=0.7.0 <0.8.0'
  crypto: '^0.9.0'
  route_hierarchical: "^0.6.0"
  intl: '>=0.11.6 <0.12.0'
transformers:
- polymer:
    entry_points: web/index.html
- $dart2js:
    environment: { PROD: "false", REST_URL: "http://laptop-dell-linux:8080/" }
    minify: false
    sourceMaps: true
    suppressHints: false
    suppressWarnings: false
