
---
spring:
  profiles: local
  data:
    mongodb:
      uri: mongodb://${MONGO_URL:localhost:27017}/facility

server:
  port: 9302

authserver:
  protocol: http
  hostname: localhost
  port: 8899
  contextPath: uaa

security:
  oauth2:
    client:
      accessTokenUri: ${authserver.protocol}://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/oauth/token
      userAuthorizationUri: ${authserver.protocol}://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/oauth/authorize
      clientId: web
    resource:
      userInfoUri: ${authserver.protocol}://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/user
      preferTokenInfo: false

