---
spring:
  profiles: local
  data:
    mongodb:
      uri: mongodb://${MONGO_URL:localhost:27017}/environment
server:
  port: 9302
authserver:
 hostname: localhost
 port: 8899
 contextPath: uaa

security:
  oauth2:
    resource:
      userInfoUri: https://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/user
      preferTokenInfo: false
