server:
  context-path: /api

security:
  user:
    password: none
  oauth2:
    sso:
      home:
        secure: false
        path: /,/**/*.html
    client:
      accessTokenUri: ${authserver.protocol}://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/oauth/token
      userAuthorizationUri: ${authserver.protocol}://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/oauth/authorize
      clientId: web
    resource:
      userInfoUri: ${authserver.protocol}://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/user
      preferTokenInfo: false

zuul:
  routes:
    resource:
          path: /resource/**
          url: http://localhost:8765/api
#    web-portal: /**
    user:
      path: /user/**
#      stripPrefix: true
      url: ${authserver.protocol}://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/user

---
spring:
  profiles: local

logging:
  level:
     org:
       springframework:
         security: DEBUG

authserver:
  protocol: http
  hostname: localhost
  port: 8899
  contextPath: uaa

---
spring:
  profiles: docker
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password

authserver:
  protocol: https
  hostname: localhost
  port: 8899
  contextPath: uaa

security:
  require_ssl: true
