server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
---
spring:
  profiles: test
security:
  basic:
    enabled: false

---
spring:
  profiles: prod
security:
  basic:
    enabled: true
  user:
      name: eureka-client
      password: ${EUREKA_PASSWORD}

---
spring:
  profiles: ssl
server:
  ssl:
    key-store: eureka-server/keystore.jks
    key-store-password: password
    key-password: password
    clientAuth: want
