server:
  context-path: /uaa

---
spring:
  profiles: local

logging:
  level:
     org:
       springframework:
         security: DEBUG

---
spring:
  profiles: docker
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password

security:
  require_ssl: true
#  oauth2:
#    client:
#      id: web
#      client-id: web
#      authorities:
#        - ROLE_CLIENT
#      authorized-grant-types: authorization_code,refresh_token,implicit,password,client_credentials
#      scope: read
#      client-secret: secret
#      resource-ids:
#        - apis
#      refresh-token-validity-seconds: 300
