spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/inventory
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    statusPageUrlPath: /structure

