server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
---
spring:
  profiles: test,local
security:
  basic:
    enabled: false

---
spring:
  profiles: docker
security:
  basic:
    enabled: true
  user:
      name: eureka-client
      password: ${EUREKA_PASSWORD}

