server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_GIT_URI:https://github.com/thomasletsch/moserp-config-repo}
          basedir: target/config

---
spring:
  profiles: docker
  cloud:
    config:
      server:
        docker:
          searchLocations: classpath:/config
